[project]
name = "malmquist"
version = "0.1.0"
description = "Malmquist"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "scipy>=1.13.1",
    "seaborn>=0.13.2",
]
